version: "3"

services:
  # Postgres
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # App
  web:
    restart: always
    env_file:
      - .env
    build: .
    links:
      - postgres:postgres
    ports:
      - "8000:8000"
    volumes:
      - ./media:/var/www/gs1_api/media
    depends_on:
      - postgres

volumes:
  pgdata:
  web: