version: "3"

services:
  # Postgres
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"

  # App
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=gsone.settings_test
      - DATABASE_HOST=postgres
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=
    links:
      - postgres:postgres
    depends_on:
      - postgres

volumes:
  pgdata:
  web: